name: Slack File Upload

on:
 pull_request:
   branches:
     - master

jobs:
  upload:
    name: Upload File to Slack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload File
        uses: kibettheophilus/slack-file-upload@v0.1.1
        with:
          file: "artifact/to/upload.pdf"
